#!/bin/bash
set -e

MM_USERNAME=${MM_USERNAME:-mmuser}
MM_PASSWORD=${MM_PASSWORD:-mmuser_password}
MM_DBNAME=${MM_DBNAME:-mattermost}

psql -v ON_ERROR_STOP=1 --username "postgres" <<- EOSQLMM
    CREATE DATABASE $MM_DBNAME;
    CREATE USER $MM_USERNAME WITH PASSWORD '$MM_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $MM_DBNAME to $MM_USERNAME;
EOSQLMM



GL_USERNAME=${DB_USER:-gitlab}
GL_PASSWORD=${DB_PASS:-password}
GL_DBNAME=${DB_NAME:-gitlabhq_production}
GL_DBEXT=${DB_EXTENSION:-pg_trgm}

psql -v ON_ERROR_STOP=1 --username "postgres" <<- EOSQLGL
    CREATE DATABASE $GL_DBNAME;
    CREATE USER $GL_USERNAME WITH PASSWORD '$GL_PASSWORD';
    CREATE EXTENSION IF NOT EXISTS $GL_DBEXT;
    GRANT ALL PRIVILEGES ON DATABASE $GL_DBNAME to $GL_USERNAME;
EOSQLGL
